# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecount',
            name='uniqueClientCount',
            field=models.IntegerField(default=0),
        ),
    ]
